config/routes.rb
PubApp::Application.routes.draw do

  devise_for :users

  resources :users do
    get 'dashboard', on: :member
    resources :articles
  end
  
  get "work", to: "works#index"
  get "work/formhub", to: "works#formhub"
  get "work/google_analytics", to: "works#google_analytics"
  get "work/lighthouseapp", to: "works#lighthouseapp"
  get "work/united_states_zoomable_map", to: "works#united_states_zoomable_map"
  get "work/river", to: "works#river"
  get "work/scatter", to: "works#scatter"
  get "work/sunburst", to: "works#sunburst"
  get "work/heat_map_of_outlets", to: "works#heat_map_of_outlets"

  get 'posts', to: 'articles#index', as: :posts
  get 'blog', to: 'articles#index', as: :posts
  put 'posts_filter', to: 'articles#index', as: :posts_filter
  get 'tag/:tag', to: 'articles#index', as: :tag

  get 'contact' => 'static_pages#contact', :as => "contact"
  get 'security' => 'static_pages#security', :as => "security"
  get 'about' => 'static_pages#about', :as => "about"
  get 'testimonials' => 'static_pages#testimonials', :as => "testimonials"
  get 'presentations' => 'static_pages#presentations', :as => "presentations"
  get "contact_us" => 'static_pages#contact_us', :as => 'contact_us'
  get "labs" => 'static_pages#labs', :as => 'labs'
  get "hacker-culture" => 'static_pages#careers'
  get "careers" => 'static_pages#careers', :as => 'careers'
  get 'cerebro' => 'static_pages#cerebro', :as => "cerebro"
  get 'products/cerebro' => 'static_pages#cerebro', :as => "cerebro"


  root :to => 'static_pages#index'
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  field :post, type: String
  field :title, type: String
  field :is_published, type: Boolean
  field :meta_keys, type: String
  field :meta_descriptions, type: String
  field :user_id, type: Integer
  #field :_id, :type => String, default: -> { name.to_s.parameterize }
  
  #ACCESSORS
  attr_accessible :post, :title, :is_published, :meta_keys, :meta_descriptions, :created_at, :user_id


  #ASSOCIATIONS
  belongs_to :user
  belongs_to :tagging, polymorphic: true



  #VALIDATIONS
  validates :post, presence: true
  validates :title, presence: true
  validates :meta_keys, presence: true, length: {minimum: 1, maximum: 1000}
  validates :meta_descriptions, presence: true, length: {minimum: 1, maximum: 200}

  #CALLBACKS  
  
  #SCOPES  

  
  #OTHER METHODS  
  #JOBS
  #PRIVATE
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :filt]
  before_filter :find_user, :except => [:index, :filt]
  
  def index
    @articles = Article.all
    @article = @articles.first
  end

  def show
    @article = @user.articles.find(params[:id])
    @meta_keys = @article.meta_keys
    @meta_descriptions = @article.meta_descriptions
    @meta_author = @article.user.name
    respond_to do |format|
       format.html
       format.js
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def create    
    @article = current_user.articles.build(params[:article])
    
      if @article.save
        redirect_to user_article_path(@article.user, @article), notice: 'Article was successfully created.' 
      else
        render action: "new" 
      end
  end

  def update

    @article = current_user.articles.find(params[:id])

    if @article.update_attributes(params[:article])
        redirect_to user_article_path(@article.user, @article), notice: 'Article was successfully updated.' 
    else
        render action: "edit"
    end

  end

  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy
    redirect_to dashboard_user_path(current_user)
  end

  def publish
    @article = current_user.articles.find(params[:id])

    if @article.update_attributes(:is_published => true)
        redirect_to dashboard_user_path(current_user), notice: 'Article was successfully published.' 
    else
        @articles = current_user.articles
        render "users#dashboard"
    end
  end

  def filt
    @articles = Tag.find(params[:id])
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.haml
#articles
	#loader-bar{:style => "display:none"}
		%h5{:style => "background-color:#FFD700; position:absolute; top:auto; right:auto; left:auto;"} Titles Loading...
	%ul.m0p0.list-unstyled
		- @articles.each do |article|
			%li.tit
				= link_to article.title, user_article_path(article.user, article), class:"title", remote: true, dis_title: article.title
				%hr.m0p0

app/views/articles/_form.html.haml
= simple_form_for([current_user, @article], :html => { :class => 'form-horizontal' }) do |f|
  = f.input :title
  = f.input :tag_list, :hint => "Add more Tags, separated by commas"
  = f.input :meta_keys, as: :text, :hint => "Add your SEO Keywords for SEO Friendly", input_html: {:rows => 2, :cols => 60}
  = f.input :meta_descriptions, as: :text, :hint => "Descriptions about Articles", input_html: {:rows => 2, :cols => 60}
  = f.input :created_at, as: :date
  = f.text_area :post, class: "col-sm-4 tinymce", :rows => 10, :cols => 10
  = f.input :user_id, as: :hidden, input_html: {value: current_user.id}
  %br
  = f.button :submit, :class => 'btn btn-default'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), user_articles_path

=tinymce
%br
%br
%br

app/views/articles/edit.html.haml
.row
	.col-sm-12
		.page-header
			%h1.m0p0 Edit your Article
	.col-sm-12
		%br
		%br
.row
	.col-sm-12
		= render partial: "form"

app/views/articles/index.html.haml
= title("blog - pykih")
- content_for :head, auto_discovery_link_tag(:rss, {action: "index"})
.row
  .col-sm-12
    .page-header
      %h1.m0p0
        = link_to "Our thoughts and experiments", posts_path, class: "red"
        = image_tag "pykih_tile_50.png", size: "40x40", class: "pull-right img-responsive"
  .col-sm-12
    %br
    %br
.row
  .col-sm-2
    %strong Tags
    %br
    %br
    %ul.m0p0.list-unstyled

    %hr
    = render partial: "layouts/shared/signup"
    %hr
    = render partial: "layouts/shared/tw"
    %hr
    = render partial: "layouts/shared/fb"
    %hr
    .img-responsive
      = link_to image_tag("slideshare.png"), "http://www.slideshare.net/ritvvijparrikh", target: "_blank"
    =# link_to image_tag("feed-icon-28x28.png"), posts_path(format: "rss")
    %br
    %br
    %br
  .col-sm-10
    .col-sm-4
      %strong Essay Titles
      %br
      %br
      %small= render 'articles'
    .col-sm-8
      #poster-bars{:style => "display:none"}
        %h5{:style => "background-color:#FFD700; position:absolute; top:auto; right:auto; left:auto;"} Article Loading...
      %p
        #title 
          - if @article.blank?
            %small.gray
              %i the article will appear here
          - else
            .table-responsive
              %table.table-striped.table-condensed
                %tr
                  %td
                    %h3.m0p0= @article.title
                    .gray{style: "font-size:12px; font-weight: 200;"}
                      Posted by
                      = @article.user.name
                      |
                      = time_ago_in_words(@article.created_at)
                      ago
                    %td &nbsp;&nbsp;
              %hr
              %br
              = @article.post.html_safe
      %br
      %br
      %h5 Please do share your views
      %br
      %div#disqus_thread{:style=>"display:none"}  

:javascript
  $(".title").click(function(){
    var disqus_title = $(this).attr("dis_title");
    var disqus_identifier = $(this).attr("dis_identify");
    var disqus_url = $(this).attr("dis_url");
    history.pushState({id: disqus_identifier}, disqus_title, disqus_url);

    var reset = function(disqus_title, disqus_identifier, disqus_url){

        DISQUS.reset({
          reload: true,
          config: function () {  
            this.page.identifier = disqus_idenfier;
            this.page.url = disqus_url;
            this.page.title = disqus_title;
            this.language = "en";
          }
        });
    };
        var disqus_config = function () { 
    	  this.language = "en";
    	};
    	
    (function() {
      var disqus_shortname = 'pykih';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq); 
    })(); 
  });

  $( ".title:first").trigger( "click" );

  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  

  function fbs_click() {u=location.href;t=document.title;window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');return false;}

app/views/articles/index.js.erb
$("#articles").html("<%= escape_javascript(render("articles")) %>");
$("#poster-bars").hide();

app/views/articles/new.html.haml
.row
	.col-sm-12
		.page-header
			%h1.m0p0 Create your New Articles
	.col-sm-12
		%br
		%br
.row
	.col-sm-12
		= render partial: "form"

app/views/articles/show.html.haml
= title("#{@article.title} - pykih")
.row
  .col-sm-12
    %ol.breadcrumb
      %li= link_to "All articles", posts_path
    .page-header
      %h1.m0p0
        = @article.title
      %p{style: "color: grey"} Posted by #{@article.user.name} | #{time_ago_in_words(@article.created_at)} ago |
  .col-sm-12
    %br
    %br
.row
  .col-sm-8
    %p= @article.post.html_safe
    %br
    %br
    %h5 Please do share your views
    %br
    %div#disqus_thread
  .col-sm-1
    %br
  .col-sm-3
    - @article.tag_list.each do |t|
      %span.label.label-default= t
      &nbsp;
    %br
    %hr
    %h5 Recommended reads
    %ul.m0p0.list-unstyled
      - @article.recommended_articles.each do |article|
        %li
          = link_to article.title, user_article_path(article.user, article), class:"glowblue"
          %hr.m0p0

:javascript

        (function() {
          var disqus_shortname = 'pykih';
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();

app/views/articles/show.js.erb
var data_url_twitter = "<%= BASE_URL  %>" + window.location.pathname;
var fb_share_img_style = "padding:2px 0 0 20px;height:26px;no-repeat top left;";
var url = "http://static.ak.facebook.com/images/share/facebook_share_icon.gif?6:26981";
var fb_share_img = "<img src='"+url+"'/>";

$("#title").html("<div class='table-responsive'><table><tr><td><h3 class='m0p0'><%= @article.title %></h3><div style='color: gray; font-size: 12px; font-weight: 200;'>Posted by <%=@article.user.name%> | <%= time_ago_in_words(@article.created_at)%> ago | <a href=<%= user_article_path(@article.user, @article)%>>Permalink</a> <% @article.tag_list.each do |t| %><span class='label label-default' style='font-size: 11px;'><%= t %></span>&nbsp;<% end %></div></td><td>&nbsp;&nbsp;</td></table></div><a href='https://twitter.com/share' class='twitter-share-button' data-url='"+ data_url_twitter  +"' data-text='<%= @article.title %>'>Tweet</a><div class='fb-send' data-href='"+ data_url_twitter +"'></div>"+ '<a rel="nofollow" href="http://www.facebook.com/share.php?u='+ data_url_twitter +'" onclick="return fbs_click()" target="_blank" class="fb_share_link">' + fb_share_img+ '</a>'+"  <hr/><br/><%= j @article.post.html_safe %>");
$("#poster-bars").hide();
$("#disqus_thread").show();